pipeline {
    agent any

    tools {
            go 'go-1.26'
            nodejs 'node20'
    }

    stages {    
        stage('Backend Unit Test') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./... 2>&1 | go-junit-report > reports.xml'
                }
            }
            post {
                always {
                    junit testResults: 'bugtracker-backend/report.xml'
                }
            }
        }
        stage('Frontend Unit Test') {
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
            post {
                always {
                    junit testResults:'bugtracker-frontend/test-results.xml'
                }
            }
        }
    }
}
