pipeline {
    agent any

    tools {
            go 'go-1.26'
            nodejs 'node20'
    }

    stages {    
        stage('Backend Unit Test') {
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
        stage('Frontend Unit Test') {
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                        npm ci
                        npm test
                    '''
                }
            }
        }
    }
}
